title: BühlAIRfrischt
copyright: 2020 Stadt Bühl
url: https://buehl.airfrischt.de
# baseurl: /clair
email: kontakt@airfrischt.de
description: BühlAIRfrischt - eine Initiative der Stadt Bühl zur Messung der Luftqualität in öffentlich zugänglichen Räumen
logo: /img/clair-cloud-blue.svg
locale: de_DE
social:
  name: Stadt Bühl
  links:
    - https://www.facebook.com/StadtBuehl
    - https://github.com/buehl
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
gems:
  - jekyll-liquify
exclude:
  - README.md
  - LICENSE.txt
